[package]
name = "firmware-maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fmm"
test = false
bench = false
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
thiserror = "1"
bytes="1.4"
quicklz="0.3.1"
crc32fast="1.3.2"
serde= {version="1.0.*", features=["derive"]}
serde_json="1.0.94"
hex = "0.4.3"