[package]
name = "app_zcash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true }
rust_tools = { workspace = true }
app_utils = { workspace = true }
bitcoin = { workspace = true }
thiserror = { workspace = true }
zcash_vendor = { workspace = true }
hex = { workspace = true }
bitvec = {version = "1.0.1", default-features = false, features = ["alloc"]}
blake2b_simd = { workspace = true }
rand_core = { workspace = true, features = ["getrandom"] }
zcash_note_encryption = "0.4.1"

[dev-dependencies]
keystore = { path = "../../keystore" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }