[package]
name = "ton_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true }
app_ton = { workspace = true }
app_utils = { workspace = true }
rust_tools = { workspace = true }
cty = { workspace = true }
cstr_core = { workspace = true }
common_rust_c = { path = "../common" }
hex = { workspace = true }
ur-registry = { workspace = true }

[features]
debug-memory = []