[package]
name = "signature_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1={ version = "0.27.0", default_features = false, features = ["alloc", "lowmemory"]} 
thiserror = { version = "1.0", package = "thiserror-core", default-features = false }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
cty = "0.2.2"
cstr_core = "0.2.6"
common_rust_c = {path = "../common"}