[package]
name = "arweave_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { path = "../../../keystore", default-features = false }
app_utils = { path = "../../../apps/utils" }
app_arweave = {path = "../../../apps/arweave"}
common_rust_c = {path = "../common"}
third_party = { path = "../../../third_party" }
cty = "0.2.2"