[package]
name = "cardano_rust_c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true}
app_cardano = { workspace = true }
third_party = { workspace = true }
app_utils = { workspace = true }
rust_tools = { workspace = true }
cty = { workspace = true }
cstr_core = { workspace = true }
itertools = { workspace = true }
hex = { workspace = true }
ur-registry = { workspace = true }
bitcoin = { workspace = true }
ed25519-bip32-core = { workspace = true }

common_rust_c = { workspace = true }

[features]
debug-memory = []