[package]
name = "app_xrp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keystore = { workspace = true, default-features = false }
app_utils = { workspace = true }
base-x = { version = "0.2.11", default-features = false }
serde = { workspace = true, default-features = false }
serde_derive = { workspace = true }
rippled_binary_codec = { git = "https://github.com/KeystoneHQ/rippled_binary_codec.git", tag = "v0.0.8" }
bytes = { version = "1.1.0", default-features = false }
bitcoin = { workspace = true }
hex = { workspace = true }
cryptoxide = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
keystore = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }