include_guard = "_LIBRUST_C_H"

after_includes = "#define SIMPLERESPONSE_C_CHAR_MAX_LEN 2048\n#define ADDRESS_MAX_LEN 128\n#define PATH_ITEM_MAX_LEN 32"

[defines]
"feature = multi-coins" = "BUILD_MULTI_COINS"

[parse]
parse_deps = true
include = [
    "rust_c",
    "common_rust_c",
    "bitcoin_rust_c",
    "wallet_rust_c",
    "btc_only_wallet_rust_c",
    "test_cmd",
    "btc_test_cmd",
    "simulator_rust_c"
]
extra_bindings = [
    "common_rust_c",
    "bitcoin_rust_c",
    "wallet_rust_c",
    "btc_only_wallet_rust_c",
    "test_cmd",
    "btc_test_cmd",
    "simulator_rust_c"
]

[parse.expand]
crates = [
    "rust_c",
    "common_rust_c",
    "bitcoin_rust_c",
    "wallet_rust_c",
    "btc_only_wallet_rust_c",
    "test_cmd",
    "btc_test_cmd",
    "simulator_rust_c"
]
default_features = false
features = ["btc-only"]